# Generated by Django 5.1.7 on 2025-04-11 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(upload_to='uploads/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('processed_video', models.FileField(blank=True, null=True, upload_to='videos/processed/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetectedFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='figures/')),
                ('category', models.CharField(choices=[('mitotic', 'Mitotic'), ('non_mitotic', 'Non-Mitotic'), ('discarded', 'Discarded')], max_length=20)),
                ('confidence', models.FloatField()),
                ('frame_number', models.IntegerField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='mitotic_app.analysis')),
            ],
        ),
    ]
