# Generated by Django 5.1.7 on 2025-04-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitotic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='hpf_height_px',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='hpf_width_px',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='mitoses_per_10_hpf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='total_hpfs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='tumor_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='x_mpp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='y_mpp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
